
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { CustomSupabaseClient } from '@/types/blog';

const SUPABASE_URL = "https://kckvcqtafgwrgkkgjqbj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtja3ZjcXRhZmd3cmdra2dqcWJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwMzA4ODcsImV4cCI6MjA1NjYwNjg4N30.cpq96xVmKgmdQorGGsmbLbY1xaOpJF0481KPuMfm04E";

// Create the standard Supabase client
const standardClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Export a custom client that extends the standard client with blog-related functionality
export const supabase = standardClient as unknown as CustomSupabaseClient;
