
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kckvcqtafgwrgkkgjqbj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtja3ZjcXRhZmd3cmdra2dqcWJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwMzA4ODcsImV4cCI6MjA1NjYwNjg4N30.cpq96xVmKgmdQorGGsmbLbY1xaOpJF0481KPuMfm04E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
